language: cpp
sudo: required
dist: trusty
group: deprecated-2017Q4
compiler:
- g++
os: 
- linux
before_install:
    - sudo apt-get install curl
    - sudo apt-get install openssl
    - sudo apt-get install libcpprest-dev 
    - cmake --version
    - curl --version
    - openssl version
    - chmod +x linux_build.sh 

script: ./linux_build.sh 

